import Logo from '@/components/Logo'
import Menu from '@/components/Menu'
import Layout from '@/components/_layout'
import Head from 'next/head'
import Image from 'next/image'
import { useSession, getProviders, signIn } from 'next-auth/react'
import { useRouter } from 'next/router'

export default function Login({ providers }: any) {
	const { data: session } = useSession()
	const router = useRouter()

	if (session) {
		router.push('/')
	}

	return (
		<>
			<Head>
				<title>Login | Pilpilan Voting</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Layout>
				<Menu />
				<div className='mx-auto flex flex-col items-center justify-center h-full text-center'>
					<Logo className='text-5xl' />
					<div className='w-1/3 mt-12'>
						{Object.values(providers).map((provider: any) => (
							<button
								onClick={() => signIn(provider.id)}
								key={provider.name}
								className='inline-flex w-full bg-white over:bg-gray-900 hover:text-white transition-all duration-300 py-2 border-2 border-gray-900 justify-center font-semibold rounded space-x-2 hover:bg-gray-900 items-center'
							>
								{provider.name === 'Google' && (
									<Image
										src={'/assets/google-icon.svg'}
										width={22}
										height={22}
										alt='google logo'
									/>
								)}
								<span>Login with {provider.name}</span>
							</button>
						))}
					</div>
				</div>
			</Layout>
		</>
	)
}

export async function getServerSideProps() {
	const providers = await getProviders()

	return {
		props: { providers },
	}
}
