import Form from '@/components/Form'
import Menu from '@/components/Menu'
import Layout from '@/components/_layout'
import Head from 'next/head'
import Image from 'next/image'
import DatePicker, { registerLocale } from 'react-datepicker'
import id from 'date-fns/locale/id'
import { useState } from 'react'
import 'react-datepicker/dist/react-datepicker.css'
import CandidateForm from '@/components/CandidateForm'
import { PlusIcon } from '@heroicons/react/24/outline'
import Button from '@/components/Button'

registerLocale('id', id)

export default function CreateVote() {
	const [startDate, setStartDate] = useState(new Date())
	const [endDate, setEndDate] = useState(new Date())

	const [candidates, setCandidates] = useState<Candidate[]>([])

	const submitCandidate = (candidate: Candidate) => {
		setCandidates(
			candidates.map(c => (c.key === candidate.key ? candidate : c))
		)
	}

	const addCandidateForm = () => {
		const newCandidate: Candidate = {
			name: '',
			key: candidates.length + 1,
			title: '',
		}

		setCandidates([...candidates, newCandidate])
	}

	const removeCandidateForm = (key: number) => {
		// List kandidat baru kecuali dengan key di atas (key:number)
		const newCandidates = candidates.filter(candidate => candidate.key !== key)

		// Re-arrange atau diurutkan ulang key-nya
		newCandidates.forEach((candidate, index) => {
			candidate.key = index + 1
		})

		setCandidates(newCandidates)
	}

	return (
		<>
			<Head>
				<title>Buat Voting | Pilpilan Voting</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Layout>
				<Menu />
				<div className='py-6'>
					<Image
						src={'/assets/buat-voting.svg'}
						width={284}
						height={198}
						alt='Buat Vote'
						priority
					/>
					<h1 className='text-4xl font-bold'>Buat Voting Baru</h1>
					<h2 className='mt-3 text-lg text-gray-600'>
						Silakan memasukkan data yang dibutuhkan
					</h2>
					<div>
						<form className='flex flex-col'>
							{/* <DetailVote> */}
							<div className='w-1/2 space-y-5'>
								<h3 className='mt-10 text-2xl font-medium'>Detail Voting</h3>
								<div className='flex flex-col mt-3'>
									<label className='mt-5 text-sm font-medium text-gray-600'>
										Judul
									</label>
									<Form
										onChange={() => {}}
										value={''}
										placeHolder={'Contoh: Voting Calon Mertua'}
										className={'mt-1 w-1/2'}
									/>
								</div>
								<div className='flex flex-col w-full'>
									<label className='text-sm text-gray-600'>
										Kapan dimulai?
									</label>
									<div className='inline-flex'>
										<DatePicker
											locale={id}
											showTimeSelect
											selected={startDate}
											onChange={date => date && setStartDate(date)}
											dateFormat={'Pp'}
											minDate={new Date()}
											className={
												'w-full py-2 px-4 bg-gray-100 border border-gray-200 rounded'
											}
										/>
										<span className='p-3 text-center textsm'>Sampai</span>
										<DatePicker
											locale={id}
											showTimeSelect
											selected={endDate}
											onChange={date => date && setEndDate(date)}
											dateFormat={'Pp'}
											minDate={startDate}
											className={
												'w-full py-2 px-4 border border-gray-200 bg-gray-100 rounded'
											}
										/>
									</div>
								</div>
							</div>
							{/* </DetailVote> */}

							{/* <Kandidat> */}
							<h3 className='mt-10 text-2xl font-medium'>Kandidat</h3>
							<div className='grid grid-cols-4 gap-4 mt-5'>
								{candidates.map((candidate: Candidate, index: number) => (
									<CandidateForm
										key={index}
										candidate={candidate}
										submitCandidate={submitCandidate}
										removeCandidateForm={removeCandidateForm}
									/>
								))}
								<div
									className='w-1/3 flex flex-col items-center justify-center cursor-pointer bg-gray-100 aspect-square text-gray-500 hover:bg-gray-900 hover:text-white rounded'
									onClick={() => addCandidateForm()}
								>
									<PlusIcon className='w-1/3' />
								</div>
							</div>
							{/* </Kandidat> */}
							{/* {JSON.stringify(candidates)} */}
							<div className='text-right mt-10'>
								<Button label='Buat Voting 🔥' type='primary' />
							</div>
						</form>
					</div>
				</div>
			</Layout>
		</>
	)
}
