import Head from 'next/head'
import Layout from '../_layout'
import Menu from '../Menu'
import Image from 'next/image'
import Button from '../Button'
import { signIn } from 'next-auth/react'

export default function RestrictedPage() {
	return (
		<>
			<Head>
				<title>Login Dulu | Pilpilan Voting</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Layout>
				<Menu />
				{/* <div className='flex flex-col items-center justify-center w-full h-screen space-y-5 text-center margin -top-16'> */}
				<div className='flex flex-col space-y-4 py-44 place-items-center'>
					<Image
						src={'/assets/restricted.svg'}
						width={220}
						height={220}
						alt='restricted'
						priority
					/>
					<h1 className='text-4xl font-bold'>Login dulu, yuk!</h1>
					<p className='text-lg'>
						Untuk mengakses halaman ini, kamu wajib login terlebih dahulu
					</p>
					<Button onClick={signIn} label='Login' type='primary' />
				</div>
			</Layout>
		</>
	)
}
