import Button from '@/components/Button'
import Form from '@/components/Form'
import Menu from '@/components/Menu'
import Layout from '@/components/_layout'
import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import { useState } from 'react'
import { useSession } from 'next-auth/react'
import RestrictedPage from '@/components/page/RestrictedPage'
import { showAlert } from '@/components/Alert'

export default function Participant() {
	const router = useRouter()

	const [code, setCode] = useState('')

	const handleSubmit = async () => {
		if (code === '') {
			showAlert({
				title: 'Waduh... 😣',
				message: 'Tolong masukkan kode yang benar',
			})
			return
		}

		await fetch('/api/participant/' + code, {
			method: 'GET',
		})
			.then(res => res.json())
			.then(data => {
				if (data?.message === 'NOT FOUND') {
					showAlert({
						title: 'Waduh... 😣',
						message: 'Kode yang kamu masukkan salah',
					})
					return
				}
				router.push('/participant/' + code)
				return
			})
	}

	const { data: session } = useSession()

	if (!session) {
		return <RestrictedPage />
	}

	return (
		<>
			<Head>
				<title>Detail Partisipan | Pilpilan Voting</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Layout>
				<Menu />
				<div className='flex flex-col items-center justify-center h-full'>
					<Image
						src={'/assets/participant.svg'}
						alt='participant'
						height={250}
						width={200}
						priority
					/>
					<h1 className='mt-6 text-4xl font-bold'>Ikutan Voting</h1>
					<h2 className='w-2/3 my-4 text-lg text-center'>
						Untuk ikutan voting, kamu harus memasukkan kode voting yang sudah di
						berikan panitia/penyelenggara
					</h2>
					<div className='w-1/3'>
						<Form
							value={code}
							onChange={setCode}
							placeHolder='Masukkan kode voting'
							className='mt-3'
						/>
					</div>
					<Button
						onClick={handleSubmit}
						label='Lanjutkan'
						type='primary'
						className='w-1/3 mt-4'
					/>
					<button className='mt-6 text-sm' onClick={() => router.push('/')}>
						Kembali
					</button>
				</div>
			</Layout>
		</>
	)
}
