import Button from '@/components/Button'
import Form from '@/components/Form'
import Menu from '@/components/Menu'
import Layout from '@/components/_layout'
import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import { useState } from 'react'

export default function Participant() {
	const router = useRouter()

	const [code, setCode] = useState('')

	const handleSubmit = () => {
		router.push('/participant/kode-voting')
	}

	return (
		<>
			<Head>
				<title>Detail Partisipan | Pilpilan Voting</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Layout>
				<Menu />
				<div className='flex items-center h-full justify-center flex-col'>
					<Image
						src={'/assets/participant.svg'}
						alt='participant'
						height={200}
						width={180}
						priority
					/>
					<h1 className='font-bold text-4xl mt-6'>Ikutan Voting</h1>
					<h2 className='w-2/3 text-lg my-4 text-center'>
						Untuk ikutan voting, kamu harus memasukkan kode voting yang sudah di
						berikan panitia/penyelenggara
					</h2>
					<div className='w-1/3'>
						<Form
							value={code}
							onChange={setCode}
							placeHolder='Masukkan kode voting'
							className='mt-3'
						/>
					</div>
					<Button
						onClick={handleSubmit}
						label='Lanjutkan'
						type='primary'
						className='w-1/3 mt-4'
					/>
					<button className='text-sm mt-6' onClick={() => router.push('/')}>
						Kembali
					</button>
				</div>
			</Layout>
		</>
	)
}
