import Head from 'next/head'
import Menu from '@/components/Menu'
import Image from 'next/image'
import Button from '@/components/Button'
import { LinkIcon, TrashIcon } from '@heroicons/react/24/outline'
import Link from 'next/link'
import Layout from '@/components/_layout'
import { useRouter } from 'next/router'
import { useSession } from 'next-auth/react'
import { NextPage } from 'next'
import useVotes from '@/lib/useVotes'
import { useEffect, useState } from 'react'
import { votes } from '@prisma/client'
import moment from 'moment'
import { showAlert } from '@/components/Alert'

const Home: NextPage = () => {
	const router = useRouter()
	const { data: session } = useSession()
	const { votes: votesApi, error, isLoading } = useVotes()

	const [votes, setVotes] = useState<Votes[]>()

	const handleDelete = (code: string) => {
		showAlert({
			title: 'Kamu yakin?',
			message: 'Ingin menghapus data?',
			onPositiveClick() {
				fetch('/api/votes/' + code, {
					method: 'DELETE',
				})
					.then(() => {
						showAlert({
							title: 'Berhasil 🔥',
							message: 'Data berhasil dihapus',
						})
						setVotes(votes?.filter(vote => vote.code !== code))
					})
					.catch(() => {
						showAlert({
							title: 'Gagal 😣',
							message: 'Data gagal dihapus',
						})
					})
			},
		})
	}

	useEffect(() => {
		if (votes) {
			setVotes(votesApi)
		}
	}, [votesApi])

	return (
		<>
			<Head>
				<title>Pilpilan Voting</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Layout>
				<Menu />
				{/* <Header> */}
				<header className='flex flex-col space-y-4 py-44 place-items-center'>
					<h1 className='text-5xl font-bold'>Ayo Voting!</h1>
					<h2 className='px-3 py-1 text-lg bg-gray-100'>
						Web Voting No 1 di Dunia
					</h2>
					<Image
						src={'/assets/header.svg'}
						width={274}
						height={243}
						alt='header'
						priority
					/>
					<div className='space-x-10'>
						<Button
							label='Buat Vote Baru'
							type='primary'
							onClick={() => router.push('/vote/create')}
						/>
						<Button
							label='Ikutan Vote'
							type='secondary'
							className='font-semibold'
							onClick={() => router.push('/participant')}
						/>
					</div>
				</header>
				{/* </Header> */}

				{/* <Table> */}
				{session && (
					<div className='mb-10'>
						<h3 className='my-5 text-lg font-bold'>Vote yang saya buat</h3>
						<table className='w-full border border-gray-100 table-auto'>
							<thead>
								<tr className='border-b border-zinc-100'>
									<th className='p-5 text-left'>No</th>
									<th className='p-5 text-left'>Judul</th>
									<th className='p-5 text-left'>Kandidat</th>
									<th className='p-5 text-left'>Kode</th>
									<th className='p-5 text-left'>Mulai</th>
									<th className='p-5 text-left'>Selesai</th>
									<th className='p-5 text-left'></th>
								</tr>
							</thead>
							<tbody>
								{votesApi && votesApi.length > 0 ? (
									votesApi.map((vote: Votes, index: number) => (
										<tr key={index}>
											<td className='p-5 text-left'>{index + 1}</td>
											<td className='p-5 font-semibold text-left text-emerald-600'>
												<Link href={`/participant/${vote.code}`}>
													{vote.title}
												</Link>
											</td>
											<td className='p-5 text-left'>
												{vote.candidates.map((c: Candidate, index: number) => (
													<span key={index} className='medium'>
														{c.name +
															(index < vote.candidates.length - 1
																? ' vs '
																: '')}
													</span>
												))}
											</td>
											<td className='p-5 font-semibold text-left'>
												{vote.code}
											</td>
											<td className='p-5 text-left'>
												{moment(vote.startDateTime).format(
													'DD, MMMM YYYY, h:mm:ss'
												)}
											</td>
											<td className='p-5 text-left'>
												{moment(vote.endDateTime).format('DD, MMMM YYYY, h:mm:ss')}
											</td>
											<td className='p-5 text-left'>
												<Link href={`/vote/${vote.code}`}>
													<LinkIcon className='w-8 h-8 p-2 transition duration-150 rounded hover:bg-yellow-100' />
												</Link>
												<button onClick={() => handleDelete(vote.code)}>
													<TrashIcon className='w-8 h-8 p-2 transition duration-150 rounded hover:bg-red-100' />
												</button>
											</td>
										</tr>
									))
								) : (
									<div className='font-semibold py-5 px-6'>Belum ada votes</div>
								)}
							</tbody>
						</table>
					</div>
				)}
				{/* </Table> */}
			</Layout>
		</>
	)
}

export default Home
