import Head from 'next/head'
import Menu from '@/components/Menu'
import Image from 'next/image'
import Button from '@/components/Button'
import { LinkIcon, TrashIcon } from '@heroicons/react/24/outline'
import Link from 'next/link'
import Layout from '@/components/_layout'
import { useRouter } from 'next/router'

export default function Home() {
	const router = useRouter()

	return (
		<>
			<Head>
				<title>Pilpilan Voting</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Layout>
				<Menu />
				{/* <Header> */}
				<header className='flex flex-col space-y-4 py-44 place-items-center'>
					<h1 className='text-5xl font-bold'>Ayo Voting!</h1>
					<h2 className='px-3 py-1 text-lg bg-gray-100'>
						Web Voting No 1 di Dunia
					</h2>
					<Image
						src={'/assets/header.svg'}
						width={274}
						height={243}
						alt='header'
						priority
					/>
					<div className='space-x-10'>
						<Button
							label='Buat Vote Baru'
							type='primary'
							onClick={() => router.push('/vote/create')}
						/>
						<Button
							label='Ikutan Vote'
							type='secondary'
							className='font-semibold'
							onClick={() => router.push('/participant')}
						/>
					</div>
				</header>
				{/* </Header> */}

				{/* <Table> */}
				<div>
					<h3 className='my-5 text-lg font-bold'>Vote yang saya buat</h3>
					<table className='w-full border border-gray-100 table-auto'>
						<thead>
							<tr className='border-b border-zinc-100'>
								<th className='p-5 text-left'>No</th>
								<th className='p-5 text-left'>Judul</th>
								<th className='p-5 text-left'>Kandidat</th>
								<th className='p-5 text-left'>Kode</th>
								<th className='p-5 text-left'>Mulai</th>
								<th className='p-5 text-left'>Selesai</th>
								<th className='p-5 text-left'></th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td className='p-5 text-left'>1</td>
								<td className='p-5 text-left'>Judul Voting</td>
								<td className='p-5 text-left'>Budi vs Anto</td>
								<td className='p-5 text-left'>BFWFWVX</td>
								<td className='p-5 text-left'>5 Maret 2023 11:00 AM</td>
								<td className='p-5 text-left'>5 Maret 2023 11:00 PM</td>
								<td className='p-5 text-left'>
									<Link href='#'>
										<LinkIcon className='w-8 h-8 p-2 transition duration-150 rounded hover:bg-yellow-100' />
									</Link>
									<Link href='#'>
										<TrashIcon className='w-8 h-8 p-2 transition duration-150 rounded hover:bg-red-100' />
									</Link>
								</td>
							</tr>
						</tbody>
					</table>
				</div>
				{/* </Table> */}
			</Layout>
		</>
	)
}
